### ISSUE TITLE
Unknown Sensor

### ISSUE THREAD

**Issue by Natrixz** [theyosh/TerrariumPI#141]
Hey Yosh,

I just found in the logs today that im getting this error alot;

2018-04-14 19:19:48,825 - INFO    - terrariumEngine    - Update done in 2.57947 seconds. Waiting for 27.42053 seconds for next round
exUnknownSensor: '/26.F22221020000/humidity'
raise exUnknownSensor(path)
File "/usr/lib/python2.7/dist-packages/ow/__init__.py", line 159, in _get
return owfs_get(object.__getattribute__(self, '_attrs')[name])
File "/usr/lib/python2.7/dist-packages/ow/__init__.py", line 347, in __getattr__
current = float(self.sensor.humidity)
File "/home/nick/TerrariumPI/terrariumSensor.py", line 211, in update
Traceback (most recent call last):
2018-04-14 19:19:46,886 - ERROR   - terrariumSensor    - '/26.F22221020000/humidity'
exUnknownSensor: '/26.F22221020000/humidity'
raise exUnknownSensor(path)
File "/usr/lib/python2.7/dist-packages/ow/__init__.py", line 159, in _get
return owfs_get(object.__getattribute__(self, '_attrs')[name])
File "/usr/lib/python2.7/dist-packages/ow/__init__.py", line 347, in __getattr__
current = float(self.sensor.humidity)
File "/home/nick/TerrariumPI/terrariumSensor.py", line 211, in update
Traceback (most recent call last):

Haven't seen this before.
Not sure if you made any changes to the sensor file recently?

**Comment by Natrixz** [comment]
Yeh it has been alot more than just 5 days.
I had to remove them and re-add them to get it to work again without errors (reboot didn't fly)

If I had to guess, my uptime was around 12 days

**Comment by Natrixz** [comment]
To add to it;
It looks to alternate between two of my sensors (same sensors)
Sometimes one of them works, sometimes it doesn't. (sometimes both work)

**Comment by theyosh** [comment]
Hmm, I am afraid this is hardware related.

With OWFS I use the libaries they provide. So I am depending / relaying on the information of OWFS. So you could try to start owhttpd and go with a browser to the Pi at port 2121. This will give a list of sensors that OWFS is seeing

**Comment by theyosh** [comment]
Is it possible to run with one sensor?
Could it be that one faulty sensor also blocks the other sensor?
Do you have backup hardware? (Maybe wise to have)

**Comment by Natrixz** [comment]
`2018-04-16 19:09:04,622 - INFO    - terrariumSensor    - Updated humidity sensor 'Links-Koud' from 85.91% to 85.92% in 0.41920 seconds
2018-04-16 19:09:03,871 - INFO    - terrariumSensor    - Updated humidity sensor 'Rechts-Warm' from 84.60% to 84.43% in 0.37835 seconds
2018-04-16 19:09:03,419 - INFO    - terrariumAudio     - Update done in 0.00002 seconds. Waiting for 29.99998 seconds for next round
2018-04-16 19:08:51,389 - INFO    - terrariumEnvironment - Update done in 0.00110 seconds. Waiting for 14.99890 seconds for next round
2018-04-16 19:08:36,693 - INFO    - terrariumEngine    - Update done in 3.27496 seconds. Waiting for 26.72504 seconds for next round
2018-04-16 19:08:36,373 - INFO    - terrariumEnvironment - Update done in 0.00107 seconds. Waiting for 14.99893 seconds for next round
2018-04-16 19:08:35,948 - INFO    - terrariumSensor    - Updated temperature sensor 'Midden' from 23.44C to 23.44C in 0.68905 seconds
2018-04-16 19:08:35,105 - INFO    - terrariumSensor    - Updated temperature sensor 'Links-Koud' from 23.78C to 23.78C in 0.13272 seconds
exUnknownSensor: '/26.C11421020000/humidity'
raise exUnknownSensor(path)
File "/usr/lib/python2.7/dist-packages/ow/__init__.py", line 159, in _get
return owfs_get(object.__getattribute__(self, '_attrs')[name])
File "/usr/lib/python2.7/dist-packages/ow/__init__.py", line 347, in __getattr__
current = float(self.sensor.humidity)
File "/home/nick/TerrariumPI/terrariumSensor.py", line 211, in update
Traceback (most recent call last):
2018-04-16 19:08:34,817 - ERROR   - terrariumSensor    - '/26.C11421020000/humidity'
exUnknownSensor: '/26.C11421020000/humidity'
raise exUnknownSensor(path)
File "/usr/lib/python2.7/dist-packages/ow/__init__.py", line 159, in _get
return owfs_get(object.__getattribute__(self, '_attrs')[name])
File "/usr/lib/python2.7/dist-packages/ow/__init__.py", line 347, in __getattr__
current = float(self.sensor.humidity)
File "/home/nick/TerrariumPI/terrariumSensor.py", line 211, in update
Traceback (most recent call last):
2018-04-16 19:08:34,813 - ERROR   - terrariumSensor    - Error updating owfs humidity sensor 'Links-Koud' with error:`

**Comment by theyosh** [comment]
Extra info:

I see these errors also when my UVB lamp is starting up. Sometimes it takes a couple of times, and during that period there is some frequency interference, because OWFS loses the humidity sensors. When the UVB light is on, it is all ok again.

I use UVB lights with a pre-starter. Like tube lights (TL-Buis)

**Comment by Natrixz** [comment]
Well yes maybe its interference or interference on the bus...it's possible.
I don't really notice it during UVB tube light start up or the jungle dawn start ups but then again that takes only a second or so.

**Comment by theyosh** [comment]
Can this ticket been closed? As I cannot solve it in software.....
