### ISSUE TITLE
Missing webcam folder

### ISSUE THREAD

**Issue by Jarve1024** [theyosh/TerrariumPI#163]
HTTP 500 error when trying to add a webcam. Turns out I needed to simply mkdir webcam

screen -r was useful. Thank you:
```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/bottle.py", line 862, in _handle
    return route.call(**args)
  File "/usr/local/lib/python2.7/dist-packages/bottle.py", line 1740, in wrapper
    rv = callback(*a, **ka)
  File "/home/terrarium/TerrariumPI/terrariumWebserver.py", line 43, in webserver_headers
    return fn(*args, **kwargs)
  File "/home/terrarium/TerrariumPI/terrariumWebserver.py", line 81, in wrapper
    return func(*a, **ka)
  File "/home/terrarium/TerrariumPI/terrariumWebserver.py", line 264, in __update_api_call
    result['ok'] = self.__terrariumEngine.set_config(path,postdata,request.files)
  File "/home/terrarium/TerrariumPI/terrariumEngine.py", line 1009, in set_config
    update_ok = self.set_webcams_config(data)
  File "/home/terrarium/TerrariumPI/terrariumEngine.py", line 698, in set_webcams_config
    self.__load_webcams(data)
  File "/home/terrarium/TerrariumPI/terrariumEngine.py", line 330, in __load_webcams
    archive)
  File "/home/terrarium/TerrariumPI/terrariumWebcam.py", line 70, in __init__
    self.update()
  File "/home/terrarium/TerrariumPI/terrariumWebcam.py", line 371, in update
    self.__get_raw_image()
  File "/home/terrarium/TerrariumPI/terrariumWebcam.py", line 124, in __get_raw_image
    self.raw_image.save(self.get_raw_image(),'jpeg',quality=terrariumWebcam.JPEG_QUALITY)
  File "/usr/lib/python2.7/dist-packages/PIL/Image.py", line 1725, in save
    fp = builtins.open(filename, "w+b")
IOError: [Errno 2] No such file or directory: 'webcam/799bd9d9c5fbfb43fbe82ec550b4b943_raw.jpg'
```

**Comment by Jarve1024** [comment]
You're correct, I'll accept pbkac on this one
