### ISSUE TITLE
3.9.0 ImportError: numpy

### ISSUE THREAD

**Issue by swekley** [theyosh/TerrariumPI#213]
I've updated to 3.9.0 using python3 and I've tried to reinstall 3 times now but i keep getting this error when I start using start.sh 3
`2018-11-21 11:06:38,000 - INFO    - terrariumWrapper     - Starting TerrariumPI server at location: http://192.168.1.29:8090 ...
ImportError: numpy.core.multiarray failed to import
Traceback (most recent call last):
  File "/home/pi/TerrariumPI/terrariumPI.py", line 20, in <module>
    from terrariumEngine import terrariumEngine
  File "/home/pi/TerrariumPI/terrariumEngine.py", line 30, in <module>
    from terrariumWebcam import terrariumWebcam, terrariumWebcamSourceException
  File "/home/pi/TerrariumPI/terrariumWebcam.py", line 6, in <module>
    import cv2
  File "/usr/local/lib/python3.5/dist-packages/cv2/__init__.py", line 3, in <module>
    from .cv2 import *
ImportError: numpy.core.multiarray failed to import`

Also tried to reinstall numpy using pip3 but that doesn't change anything

Oh and btw, the installer doesn't add the 3 after start.sh in /etc/rc.local

**Comment by swekley** [comment]
Yep I've only ran it with the 3 after install.sh.
I just installed 3.9.0 on a fresh raspbian installation so I'll check if it works this way.

**Comment by swekley** [comment]
Now I'm getting
`2018-11-21 20:32:03,000 - INFO    - terrariumWrapper     - Starting TerrariumPI server at location: http://192.168.1.38:8090 ...                                                                           
Traceback (most recent call last):                                                                                                                                                                         
  File "/home/pi/TerrariumPI/terrariumPI.py", line 20, in <module>                                                                                                                                         
    from terrariumEngine import terrariumEngine                                                                                                                                                            
  File "/home/pi/TerrariumPI/terrariumEngine.py", line 30, in <module>                                                                                                                                     
    from terrariumWebcam import terrariumWebcam, terrariumWebcamSourceException                                                                                                                            
  File "/home/pi/TerrariumPI/terrariumWebcam.py", line 6, in <module>                                                                                                                                      
    import cv2                                                                                                                                                                                             
  File "/usr/local/lib/python3.5/dist-packages/cv2/__init__.py", line 3, in <module>                                                                                                                       
    from .cv2 import *                                                                                                                                                                                     
ImportError: libImath-2_2.so.12: cannot open shared object file: No such file or directory    `

**Comment by theyosh** [comment]
Yes... the last error I know how to fix... Python3 is still not fully tested... so it could miss some packages..

`sudo apt install libilmbase12`

**Comment by swekley** [comment]
> Yes... the last error I know how to fix... Python3 is still not fully tested... so it could miss some packages..
> 
> `sudo apt install libilmbase12`

After that I get
`2018-11-21 20:57:24,000 - INFO    - terrariumWrapper     - Starting TerrariumPI server at location: http://192.168.1.38:8090 ...
Traceback (most recent call last):
  File "/home/pi/TerrariumPI/terrariumPI.py", line 20, in <module>
    from terrariumEngine import terrariumEngine
  File "/home/pi/TerrariumPI/terrariumEngine.py", line 30, in <module>
    from terrariumWebcam import terrariumWebcam, terrariumWebcamSourceException
  File "/home/pi/TerrariumPI/terrariumWebcam.py", line 6, in <module>
    import cv2
  File "/usr/local/lib/python3.5/dist-packages/cv2/__init__.py", line 3, in <module>
    from .cv2 import *
ImportError: libIlmImf-2_2.so.22: cannot open shared object file: No such file or directory`

**Comment by theyosh** [comment]
That is: `sudo apt install libopenexr22`

**Comment by swekley** [comment]
> That is: `sudo apt install libopenexr22`

then still the same error :/
`2018-11-21 21:08:26,000 - INFO    - terrariumWrapper     - Starting TerrariumPI server at location: http://192.168.1.38:8090 ...
ImportError: numpy.core.multiarray failed to import
Traceback (most recent call last):
  File "/home/pi/TerrariumPI/terrariumPI.py", line 20, in <module>
    from terrariumEngine import terrariumEngine
  File "/home/pi/TerrariumPI/terrariumEngine.py", line 30, in <module>
    from terrariumWebcam import terrariumWebcam, terrariumWebcamSourceException
  File "/home/pi/TerrariumPI/terrariumWebcam.py", line 6, in <module>
    import cv2
  File "/usr/local/lib/python3.5/dist-packages/cv2/__init__.py", line 3, in <module>
    from .cv2 import *
ImportError: numpy.core.multiarray failed to import`

**Comment by theyosh** [comment]
Sorry, my fault. Your listing is correct. It needs to be: `multiarray.cpython-35m-arm-linux-gnueabihf.so`

Hmm, strange... I do have some time now, so you can send info to: `github.com@theyosh.nl` and I will have a look
