### ISSUE TITLE
New install on Pi 3

### ISSUE THREAD

**Issue by Swiftnesses** [theyosh/TerrariumPI#215]
Hi,

I'm trying to test things on a new Pi 3.

On the final step of the install 'module emails' it seems to hang for 10 minutes or so, but says complete, so not sure that's related... sadly after install and reboot I get no UI (even if I start the server manually and it says 'started'...

Is there anything I can check?

Note 1: I've tried installing it again, it goes really fast with exception of the 'module emails', no errors.

**Comment by Swiftnesses** [comment]
Managed to grab an error:

`  File "/home/pi/TerrariumPI/terrariumNotification.py", line 19, in <module>
    import emails
ImportError: No module named emails
2018-11-24 15:58:04,000 - INFO    - terrariumWrapper     - Restart counter: 1/5
2018-11-24 15:58:04,000 - INFO    - terrariumWrapper     - Restarting in 10 seconds after running for 1 seconds. Press Ctrl+C now to terminate TerrariumPI.
10 9 8 7 6 5 4 3 2 1 restart!
2018-11-24 15:58:21,000 - INFO    - terrariumWrapper     - Starting TerrariumPI server at location: http://192.168.1.156:8090 ...
Traceback (most recent call last):
  File "/home/pi/TerrariumPI/terrariumPI.py", line 17, in <module>
    import terrariumLogging
  File "/home/pi/TerrariumPI/terrariumLogging.py", line 17, in <module>
    from terrariumNotification import terrariumNotification
  File "/home/pi/TerrariumPI/terrariumNotification.py", line 19, in <module>
    import emails
ImportError: No module named emails
2018-11-24 15:58:22,000 - INFO    - terrariumWrapper     - Restart counter: 2/5
2018-11-24 15:58:22,000 - INFO    - terrariumWrapper     - Restarting in 10 seconds after running for 1 seconds. Press Ctrl+C now to terminate TerrariumPI.
10 9 8 7 6 5 4 3 2 1 restart!
2018-11-24 15:58:33,000 - INFO    - terrariumWrapper     - Starting TerrariumPI server at location: http://192.168.1.156:8090 ...
Traceback (most recent call last):
  File "/home/pi/TerrariumPI/terrariumPI.py", line 17, in <module>
    import terrariumLogging
  File "/home/pi/TerrariumPI/terrariumLogging.py", line 17, in <module>
    from terrariumNotification import terrariumNotification
  File "/home/pi/TerrariumPI/terrariumNotification.py", line 19, in <module>
    import emails
ImportError: No module named emails
2018-11-24 15:58:33,000 - INFO    - terrariumWrapper     - Restart counter: 3/5
2018-11-24 15:58:33,000 - INFO    - terrariumWrapper     - Restarting in 10 seconds after running for 0 seconds. Press Ctrl+C now to terminate TerrariumPI.
10 9 8 7 6 5 4 3 2 1 restart!
2018-11-24 15:58:44,000 - INFO    - terrariumWrapper     - Starting TerrariumPI server at location: http://192.168.1.156:8090 ...
Traceback (most recent call last):
  File "/home/pi/TerrariumPI/terrariumPI.py", line 17, in <module>
    import terrariumLogging
  File "/home/pi/TerrariumPI/terrariumLogging.py", line 17, in <module>
    from terrariumNotification import terrariumNotification
  File "/home/pi/TerrariumPI/terrariumNotification.py", line 19, in <module>
    import emails
ImportError: No module named emails
2018-11-24 15:58:45,000 - INFO    - terrariumWrapper     - Restart counter: 4/5
2018-11-24 15:58:45,000 - INFO    - terrariumWrapper     - Restarting in 10 seconds after running for 1 seconds. Press Ctrl+C now to terminate TerrariumPI.
10 9 8 7 6 5 4 3 2 1 restart!
2018-11-24 15:58:55,000 - INFO    - terrariumWrapper     - Starting TerrariumPI server at location: http://192.168.1.156:8090 ...
Traceback (most recent call last):
  File "/home/pi/TerrariumPI/terrariumPI.py", line 17, in <module>
    import terrariumLogging
  File "/home/pi/TerrariumPI/terrariumLogging.py", line 17, in <module>
    from terrariumNotification import terrariumNotification
  File "/home/pi/TerrariumPI/terrariumNotification.py", line 19, in <module>
    import emails
ImportError: No module named emails
`

**Comment by theyosh** [comment]
Please rerun the installer. I think installation of emails modules did not fully complete

**Comment by Swiftnesses** [comment]
I tried, trying a manual install using the above commands now...

**Comment by Swiftnesses** [comment]
I had to manually install lxml first....

Used: sudo apt-get install python-lxml

**Comment by Swiftnesses** [comment]
@Marvv90 Which Pi version do you have?

**Comment by Marvv90** [comment]
Pi3 Model B v. 1.2
