### ISSUE TITLE
[BUG]: ImportError: No module named bme280

### ISSUE THREAD

**Issue by duenni** [theyosh/TerrariumPI#524]
**Setup:**
 - Python version: 3
 - Raspberry PI: 3B

**Describe the bug**
Did `sudo apt-get upgrade`. Afterwards I upgraded from 3.9.8. to 3.9.9 as described in Readme. Ran into this bug #495, did `sudo pip3 install gevent==20.9.0`. Rebooted, TerrariumPi did not start up, ran installer again. Now I get this:
```
2021-02-27 11:10:52,000 - INFO    - terrariumWrapper     - Starting TerrariumPI server at location: http://192.168.178.203:8090 ...
Traceback (most recent call last):
  File "/home/pi/TerrariumPI/terrariumPI.py", line 24, in <module>
    from terrariumEngine import terrariumEngine
  File "/usr/local/lib/python2.7/dist-packages/gevent/builtins.py", line 96, in __import__
    result = _import(*args, **kwargs)
  File "/home/pi/TerrariumPI/terrariumEngine.py", line 31, in <module>
    from terrariumSensor import terrariumSensor
  File "/usr/local/lib/python2.7/dist-packages/gevent/builtins.py", line 96, in __import__
    result = _import(*args, **kwargs)
  File "/home/pi/TerrariumPI/terrariumSensor.py", line 517, in <module>
    from terrariumI2CSensor import terrariumSHT2XSensor, terrariumHTU21DSensor, terrariumSi7021Sensor, terrariumBME280Sensor, terrariumChirpSensor, terrariumVEML6075Sensor, terrariumSHT3XSensor, terrariumSHT3XDSensor, terrariumMLX90614Sensor, terrariumAM2320Sensor, terrariumAMG8833Sensor, terrariumCCS811Sensor
  File "/usr/local/lib/python2.7/dist-packages/gevent/builtins.py", line 96, in __import__
    result = _import(*args, **kwargs)
  File "/home/pi/TerrariumPI/terrariumI2CSensor.py", line 10, in <module>
    import bme280
  File "/usr/local/lib/python2.7/dist-packages/gevent/builtins.py", line 96, in __import__
    result = _import(*args, **kwargs)
ImportError: No module named bme280
2021-02-27 11:10:55,000 - INFO    - terrariumWrapper     - Restart counter: 1/5
```
Tried `sudo pip3 install RPi.bme280` but that doesn't fix it.

**To Reproduce / Installation steps**
Update from 3.9.8 to 3.9.9

**Expected behavior**
TerrariumPi should start up.

**Screenshots**
<img width="833" alt="Bildschirmfoto 2021-02-27 um 11 25 45" src="https://user-images.githubusercontent.com/4258185/109384653-a0304680-78ee-11eb-9fab-69012854b465.png">

**Additional context**
```
$ uname -a
Linux terrariumpi 5.10.11-v7+ #1399 SMP Thu Jan 28 12:06:05 GMT 2021 armv7l GNU/Linux
```

**Comment by duenni** [comment]
Oh nevermind. I have to use `sudo ./start.sh 3` instead of `sudo ./start.sh` to start TerraiumPi with Python3. It starts without issues then.
