### ISSUE TITLE
[BUG]: v4 "AttributeError: module 'brotli' has no attribute 'error'"

### ISSUE THREAD

**Issue by campZero** [theyosh/TerrariumPI#584]
**Setup:**
 - Python version: 3
 - Raspberry PI: 4

**Describe the bug**
Service fails to start, journalctl reveals this as traceback:
```
Aug 11 23:40:08 terrariumpi python[1217]: Traceback (most recent call last):
Aug 11 23:40:08 terrariumpi python[1217]:   File "/home/pi/TerrariumPI/terrariumPI.py", line 13, in <module>
Aug 11 23:40:08 terrariumpi python[1217]:     from terrariumEngine import terrariumEngine
Aug 11 23:40:08 terrariumpi python[1217]:   File "/home/pi/TerrariumPI/terrariumEngine.py", line 2, in <module>
Aug 11 23:40:08 terrariumpi python[1217]:     import terrariumLogging
Aug 11 23:40:08 terrariumpi python[1217]:   File "/home/pi/TerrariumPI/terrariumLogging.py", line 15, in <module>
Aug 11 23:40:08 terrariumpi python[1217]:     from terrariumNotification import terrariumNotification
Aug 11 23:40:08 terrariumpi python[1217]:   File "/home/pi/TerrariumPI/terrariumNotification.py", line 11, in <module>
Aug 11 23:40:08 terrariumpi python[1217]:     from terrariumDatabase import NotificationMessage, NotificationService
Aug 11 23:40:08 terrariumpi python[1217]:   File "/home/pi/TerrariumPI/terrariumDatabase.py", line 6, in <module>
Aug 11 23:40:08 terrariumpi python[1217]:     from terrariumUtils import terrariumUtils
Aug 11 23:40:08 terrariumpi python[1217]:   File "/home/pi/TerrariumPI/terrariumUtils.py", line 8, in <module>
Aug 11 23:40:08 terrariumpi python[1217]:     import requests
Aug 11 23:40:08 terrariumpi python[1217]:   File "/home/pi/TerrariumPI/venv/lib/python3.7/site-packages/requests/__init__.py", line 43, in <module>
Aug 11 23:40:08 terrariumpi python[1217]:     import urllib3
Aug 11 23:40:08 terrariumpi python[1217]:   File "/home/pi/TerrariumPI/venv/lib/python3.7/site-packages/urllib3/__init__.py", line 13, in <module>
Aug 11 23:40:08 terrariumpi python[1217]:     from .connectionpool import HTTPConnectionPool, HTTPSConnectionPool, connection_from_url
Aug 11 23:40:08 terrariumpi python[1217]:   File "/home/pi/TerrariumPI/venv/lib/python3.7/site-packages/urllib3/connectionpool.py", line 40, in <module>
Aug 11 23:40:08 terrariumpi python[1217]:     from .response import HTTPResponse
Aug 11 23:40:08 terrariumpi python[1217]:   File "/home/pi/TerrariumPI/venv/lib/python3.7/site-packages/urllib3/response.py", line 157, in <module>
Aug 11 23:40:08 terrariumpi python[1217]:     class HTTPResponse(io.IOBase):
Aug 11 23:40:08 terrariumpi python[1217]:   File "/home/pi/TerrariumPI/venv/lib/python3.7/site-packages/urllib3/response.py", line 390, in HTTPResponse
Aug 11 23:40:08 terrariumpi python[1217]:     DECODER_ERROR_CLASSES += (brotli.error,)
Aug 11 23:40:08 terrariumpi python[1217]: AttributeError: module 'brotli' has no attribute 'error'
Aug 11 23:40:08 terrariumpi systemd[1]: terrariumpi.service: Main process exited, code=exited, status=1/FAILURE
```

**To Reproduce / Installation steps**
Fresh install of Raspian lite, apt update/upgrade
Installed v4 as per instructions.

I tried to re-install brotli and urllib3 with `pip3 install *package* --upgrade --force-reinstall`, that didn't help either.
It might not be on your side, but I couldn't find any other help related to brotli so posting here.
Added: also tried to `pip3 install requests --upgrade --force-reinstall`, didn't help either.

**Comment by campZero** [comment]
Made yet another fresh install as above - and everything works, so I have no idea what that was.
