### ISSUE TITLE
Error installing 4.0

### ISSUE THREAD

**Issue by ericmcgomes** [theyosh/TerrariumPI#598]
**Setup:**
 - TerrariumPI version: 4
 - Python version: 3
 - Raspberry PI: 3B

**Describe the bug**
I have a raspberry pi 3B running for years and tried to upgrade to 4.0. When I installed the new versions, the server didn't started up. In the log, it just it's trying to start over and over:
```
2021-08-27 00:09:01,900 - INFO    - terrariumEngine      - Starting TerrariumPI 4.0.0 ...
2021-08-27 00:09:02,226 - INFO    - terrariumEngine      - Loaded 28 settings in 0.32 seconds.
2021-08-27 00:11:18,304 - INFO    - terrariumEngine      - Starting TerrariumPI 4.0.0 ...
2021-08-27 00:11:18,463 - INFO    - terrariumEngine      - Loaded 28 settings in 0.15 seconds.
2021-08-27 00:13:35,158 - INFO    - terrariumEngine      - Starting TerrariumPI 4.0.0 ...
2021-08-27 00:13:35,316 - INFO    - terrariumEngine      - Loaded 28 settings in 0.15 seconds.
2021-08-27 00:15:51,195 - INFO    - terrariumEngine      - Starting TerrariumPI 4.0.0 ...
2021-08-27 00:15:51,352 - INFO    - terrariumEngine      - Loaded 28 settings in 0.15 seconds.
```

Thinking it was possible to be some enviroment issue, I've made a fresh install of Raspberry Pi OS Lite, but had no luck.

Sorry, I did not found how to turn the debug mode on, this version.

Trying to run the terrariumPI directly inside the virtualenv, I got an error of no module named mitemp_bt:

```
(venv) pi@raspberrypi:~/TerrariumPI $ python terrariumPI.py
2021-08-27 00:29:52,511 - INFO    - terrariumEngine      - Starting TerrariumPI 4.0.0 ...
2021-08-27 00:29:52,672 - INFO    - terrariumEngine      - Loaded 28 settings in 0.16 seconds.
Traceback (most recent call last):
  File "terrariumPI.py", line 16, in <module>
    terrariumEngine = terrariumEngine(__version__)
  File "/home/pi/TerrariumPI/terrariumEngine.py", line 114, in __init__
    self.webserver = terrariumWebserver(self)
  File "/home/pi/TerrariumPI/terrariumWebserver.py", line 54, in __init__
    self.__routes()
  File "/home/pi/TerrariumPI/terrariumWebserver.py", line 227, in __routes
    self.api.routes(self.bottle)
  File "/home/pi/TerrariumPI/terrariumAPI.py", line 157, in routes
    all_sensor_types = '|'.join(terrariumSensor.sensor_types)
  File "/home/pi/TerrariumPI/terrariumUtils.py", line 37, in __get__
    return classmethod(self.fget).__get__(None, owner)()
  File "/home/pi/TerrariumPI/hardware/sensor/__init__.py", line 104, in sensor_types
    for sensor in __cls__.available_sensors:
  File "/home/pi/TerrariumPI/terrariumUtils.py", line 37, in __get__
    return classmethod(self.fget).__get__(None, owner)()
  File "/home/pi/TerrariumPI/hardware/sensor/__init__.py", line 87, in available_sensors
    for (hardware_type, sensor) in __cls__.available_hardware.items():
  File "/home/pi/TerrariumPI/terrariumUtils.py", line 37, in __get__
    return classmethod(self.fget).__get__(None, owner)()
  File "/home/pi/TerrariumPI/hardware/sensor/__init__.py", line 61, in available_hardware
    imported_module = import_module( '.' + file.stem, package='{}'.format(__name__))
  File "/usr/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/pi/TerrariumPI/hardware/sensor/mitemp_sensor.py", line 4, in <module>
    from mitemp_bt.mitemp_bt_poller import MiTempBtPoller, MI_TEMPERATURE, MI_HUMIDITY, MI_BATTERY
ModuleNotFoundError: No module named 'mitemp_bt'
```

The odd is that the library seems to be installed inside the virtualenv:

```
(venv) pi@raspberrypi:~/TerrariumPI $ python -m pip show mitemp_bt
Name: mitemp-bt
Version: 0.0.4
Summary: Library to read data from Mi Temperature and Humidity Sensor (V2) using Bluetooth LE with LCD display
Home-page: https://github.com/ratcashdev/mitemp
Author: ratcashdev
Author-email: developer@ratcash.net
License: MIT
Location: /home/pi/TerrariumPI/venv/lib/python3.7/site-packages
Requires: btlewrap
Required-by:
```

**Comment by theyosh** [comment]
I will close it now, as I have fixed the version for mitemp-bt module.
