### ISSUE TITLE
[FEATURE]: Docker Image

### ISSUE THREAD

**Issue by alec-pinson** [theyosh/TerrariumPI#620]
**Is your feature request related to a problem? Please describe.**
Hi, really cool setup btw, just wondering if you'd ever looked into creating a docker image for this?

I think it could provide a lot of benefits (I'm happy to do the work and trial it if you think it's worth looking into)
- Easy upgrades/rollback between versions
- Maybe easier to develop/test
- No need to wait ages for the install, just pull the image and run it

**Describe the solution you'd like**
I'd like to be able to `docker run theyosh/terrariumpi:4.0.0` on my raspberry pi :)

**Comment by alec-pinson** [comment]
I decided to throw together a 'working' example.


# Commands
### Build image for raspberry pi
```sh
docker buildx build --platform linux/arm/v7 --progress=plain -t theyosh/terrariumpi:4.0.0 .
```
### Build and push to docker registry
```sh
docker buildx build --platform linux/arm/v7 --progress=plain -t theyosh/terrariumpi:4.0.0 --push .
```

### Run the container
```
docker run -d -t --privileged -p 8090:8090 -v /<your-db-file-location>.db:/TerrariumPI/history.db --name terrariumpi theyosh/terrariumpi:4.0.0
```

# Dockerfile

```dockerfile
# python builder, help keep image small
FROM python:3.8.0 as builder
ENV BASEDIR=/TerrariumPI
# Setup python virtual env
RUN python -m venv /opt/venv
ENV PATH="/opt/venv/bin:$PATH"
# picamera - https://github.com/waveform80/picamera/issues/578
ENV READTHEDOCS=True
# rpi.gpio - https://askubuntu.com/questions/1290037/error-while-installing-rpi-gpio-as-error-command-errored-out-with-exit-status
ENV CFLAGS=-fcommon
# cryptography - https://stackoverflow.com/questions/66118337/how-to-get-rid-of-cryptography-build-error
ENV CRYPTOGRAPHY_DONT_BUILD_RUST=1
RUN apt-get update && apt-get install -y --no-install-recommends libxml2-dev libxslt1-dev libasound-dev portaudio19-dev libportaudio2 libportaudiocpp0 ffmpeg python3-lxml \
    build-essential make gcc dpkg-dev libjpeg-dev \
  && pip install --upgrade pip && pip install wheel \
  && pip install python-dateutil rpi.gpio psutil picamera pigpio requests gpiozero untangle uptime bottle bottle_websocket pylibftdi \
    pyalsaaudio pyserial python-twitter python-pushover requests[socks] Adafruit-SHT31 bluepy pywemo pyownet emails mh-z19 icalendar melopero-amg8833 \
    PCA9685-driver pyfiglet RPi.bme280 gevent==20.9.0 meross-iot==0.2.2.3 iCalEvents adafruit-circuitpython-sht31d mitemp_bt asyncio \
    luma.oled cryptography==3.4.6 poetry zope.interface twisted numpy
WORKDIR /${BASEDIR}
COPY .git .git
RUN git submodule init \
  && git submodule update \
  && cd gentelella && git checkout 1.4.0 \
  && cd ${BASEDIR}/Bright-Pi && python3 setup.py install \
  && cd ${BASEDIR}/Adafruit_Python_DHT && pip3 uninstall -y -q Adafruit_DHT 2> /dev/null && python3 setup.py install --force-pi \
  && cd ${BASEDIR}/python-kasa && poetry build && pip3 install -U dist/python_kasa-*.whl \
  && cd ${BASEDIR}/8relay-rpi/python/8relay && python3 setup.py install
RUN rm -rf ${BASEDIR}/.git

# remove git dir from code copy to help keep image smaller
FROM python:3.8.0 as remove_git_dir
WORKDIR /TerrariumPI
COPY . .
RUN rm -rf .git

# actual image
FROM python:3.8.0-slim-buster
ENV DEBIAN_FRONTEND=noninteractive \
    TZ=Europe/London \
    PATH="/opt/venv/bin:$PATH" \
    PYTHONPATH=/usr/lib/python3/dist-packages
RUN apt-get update && apt-get install -y gnupg ca-certificates \
  && echo "deb http://raspbian.raspberrypi.org/raspbian/ buster main contrib non-free rpi" > /etc/apt/sources.list.d/raspberrypi.list \
  && echo "deb http://archive.raspberrypi.org/debian/ buster main" >> /etc/apt/sources.list.d/raspberrypi.list \
  && echo "deb [arch=armhf] https://download.docker.com/linux/raspbian buster stable" > /etc/apt/sources.list.d/docker.list \
  && apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 9165938D90FDDD2E 82B129927FA3303E 7EA0A9C3F273FCD8 \
  && rm -rf /var/lib/apt/lists/* \
  && apt-get update \
  && apt-get install -y --no-install-recommends \
    libftdi1 screen git subversion watchdog build-essential i2c-tools pigpio owserver sqlite3 vlc-bin ffmpeg libfreetype6-dev libjpeg-dev \
    libasound2-dev sispmctl lshw libffi-dev ntp libglib2.0-dev rng-tools libatlas3-base libgstreamer0.10-0 libgstreamer1.0-0 libopenexr23 \
    libgtk-3-0 libxml2-dev libxslt1-dev libgpiod2 python3-mediainfodll python3-smbus python3-opencv iproute2 \
  && apt-get autoremove -y && rm -rf /var/lib/apt/lists/* \
  && rm -rf /usr/lib/python3/dist-packages/numpy /usr/lib/python3/dist-packages/numpy-1.16.2.egg-info
COPY --from=builder /opt/venv /opt/venv
RUN ln -s /usr/lib/python3/dist-packages/cv2.cpython-37m-arm-linux-gnueabihf.so /opt/venv/lib/python3.8/site-packages/cv2.so && mv /usr/lib/python3.7/gettext.py /usr/local/lib/python3.8/gettext.py
WORKDIR /TerrariumPI
COPY --from=builder /TerrariumPI/ /TerrariumPI/.
COPY --from=remove_git_dir /TerrariumPI /TerrariumPI
CMD ["/TerrariumPI/start.sh", "3", "run"]
```

# Comments

Sadly it's not so easy to develop/test releases faster because you can't run it on a mac for example:-
```
2021-11-05 14:43:46,000 - INFO    - terrariumWrapper     - Starting TerrariumPI server at location: http://172.17.0.3:8090 ...
Traceback (most recent call last):
  File "/TerrariumPI/terrariumPI.py", line 21, in <module>
    import terrariumLogging
  File "/TerrariumPI/terrariumLogging.py", line 17, in <module>
    from terrariumNotification import terrariumNotification
  File "/TerrariumPI/terrariumNotification.py", line 4, in <module>
    import RPi.GPIO as GPIO
  File "/opt/venv/lib/python3.8/site-packages/RPi/GPIO/__init__.py", line 23, in <module>
    from RPi._GPIO import *
RuntimeError: This module can only be run on a Raspberry Pi!
```

I don't have any sensors or anything to test with at the moment, I've ordered a few bits, however this is an example running on a pi:-
```sh
alec@terrarium-pi:~$ docker run -d -t --privileged -p 8090:8090 -v /terrariumpi.db:/TerrariumPI/history.db --name terrariumpi theyosh/terrariumpi:4.0.0
fb429933e069e86406eed60451ea561a0edba5f7e4fd02e2012ee9bcbdec01c1
alec@terrarium-pi:~$ docker ps
CONTAINER ID        IMAGE                       COMMAND                  CREATED             STATUS              PORTS                    NAMES
fb429933e069        theyosh/terrariumpi:4.0.0   "/TerrariumPI/start.…"   4 seconds ago       Up 2 seconds        0.0.0.0:8090->8090/tcp   terrariumpi
alec@terrarium-pi:~$ docker logs -f terrariumpi
2021-11-05 14:57:58,000 - INFO    - terrariumWrapper     - Starting TerrariumPI server at location: http://172.17.0.2:8090 ...
2021-11-05 14:58:11,280 - WARNING - terrariumSensor      - OWFS file system is not actve / installed on this device! If this is not correct, try 'i2cdetect -y 1' to see if device is connected.
2021-11-05 14:58:11,630 - WARNING - terrariumBluetoothSensor - Bluetooth scanning is not enabled for normal users or there are zero Bluetooth LE devices available.... bluetooth is disabled!
terrariumMiTempSensor exception
Management not available (permissions problem?)
terrariumMiTempSensor exception
Management not available (permissions problem?)
terrariumMiTempSensor exception
Management not available (permissions problem?)
terrariumMiTempSensor exception
Management not available (permissions problem?)
terrariumMiTempSensor exception
Management not available (permissions problem?)
terrariumMiTempSensor exception
Management not available (permissions problem?)
terrariumMiTempSensor exception
Management not available (permissions problem?)
terrariumMiTempSensor exception
Management not available (permissions problem?)
terrariumMiTempSensor exception
Management not available (permissions problem?)
terrariumMiTempSensor exception
Management not available (permissions problem?)
2021-11-05 14:58:12,032 - WARNING - terrariumBluetoothSensor - Bluetooth scanning is not enabled for normal users or there are zero Bluetooth LE devices available.... bluetooth is disabled!
No GEMBIRD SiS-PM found. Check USB connections, please!
2021-11-05 14:58:22,000 - INFO    - terrariumWebserver   - Running webserver at :::8090
```


I don't know what you think of all of this but I had fun playing around anyways :)

**Comment by theyosh** [comment]
Hi,

sorry for not replying earlier. But I am not that docker fan... It is fine it is there, but somehow, I always ending up not working... :)

So, that is way I did not start with that. Also, there are some settings that are needed, which can't be done with docker.

I need the Raspberry PI overlay features for 1 wire, i2c and the camera. Which is a bit difficult with Docker. 
And I need access to the system /sys/bus/ etc.

And in the above message, you see Bluetooth errors. So, I do not know how to use Bluetooth inside Docker.
Also with the GPIO library. That means testing on a Raspberry PI. Which I am already doing, but with Docker, that would take more time that I do not have....

So, I do appreciate the effort, but I think it is not possible to use Docker with this. I depend (to much) on the Raspberry Pi hardware. And that is why I did not start with Docker.

So I leave it up to you if you think you can make it work... My knowledge of Docker is not good enough, and I like to stick to programming... :)

**Comment by theyosh** [comment]
And I see you are using the old TP3 for testing/building. Please try TP4: https://github.com/theyosh/TerrariumPI/tree/4.x.y.z
If you want to try again. The installation is a bit different. Less apt packages, and I use wheel packages for Python, which saves a lot of compiling time.

**Comment by alec-pinson** [comment]
Hi woops you're right I cloned the wrong branch. I have used docker with GPIO pins in the past but as you say you use a lot of different bits of the Raspberry Pi hardware + you make changes to /boot etc so I'm not too sure if it will work either.
I will test/trial abit further with TP4 and Docker just to see if it is worth having this option for people and get back to you :)

**Comment by alec-pinson** [comment]
Hi so I did a bit of a test (I only have a SHT3x sensor) and it looks a lot better now with TP4 but there is maybe 1 error I'm not sure about regarding usb connections

```
alec@terrarium-pi:~/TerrariumPI$ docker run --net=host --privileged -v /terrariumpi.db:/TerrariumPI/terrariumpi.db -v /terrariumpi.db-shm:/TerrariumPI/terrariumpi.db-shm -v /terrariumpi.db-wal:/TerrariumPI/terrariumpi.db-wal theyosh/terrariumpi:4.0.0
2021-11-11 12:03:31,730 - INFO    - terrariumEngine       - Starting TerrariumPI 4.0.0 ...
2021-11-11 12:03:31,845 - INFO    - terrariumEngine       - Loaded 28 settings in 0.11 seconds.
2021-11-11 12:03:33,086 - INFO    - terrariumEngine       - Loading existing sensors from database.
2021-11-11 12:03:33,319 - INFO    - terrariumEngine       - Loaded sensor sht3x humidity named 'humidity' at address '0x44' with value 60.32% in 0.22 seconds.
2021-11-11 12:03:33,325 - INFO    - terrariumEngine       - Loaded sensor sht3x temperature named 'temperature' at address '0x44' with value 20.38C in 0.00 seconds.
2021-11-11 12:03:33,327 - INFO    - terrariumEngine       - Scanning for new sensors ...
2021-11-11 12:03:39,762 - INFO    - terrariumEngine       - Loaded 2 sensors in 6.68 seconds.
2021-11-11 12:03:39,765 - INFO    - terrariumEngine       - Loading existing relays from database.
2021-11-11 12:03:39,782 - INFO    - terrariumEngine       - Scanning for new relays ...
No GEMBIRD SiS-PM found. Check USB connections, please!
2021-11-11 12:03:50,896 - INFO    - terrariumEngine       - Loaded 0 relays in 11.13 seconds.2021-11-11 12:03:50,898 - INFO    - terrariumEngine       - Loading existing buttons from database.
2021-11-11 12:03:50,914 - INFO    - terrariumEngine       - Loaded 0 buttons in 0.02 seconds.
2021-11-11 12:03:50,916 - INFO    - terrariumEngine       - Loading existing webcams from database.
2021-11-11 12:03:50,928 - INFO    - terrariumEngine       - Loaded 0 webcams in 0.01 seconds.
2021-11-11 12:03:50,930 - INFO    - terrariumEngine       - Loading existing enclosures from database.
2021-11-11 12:03:50,943 - INFO    - terrariumEngine       - Loaded 0 enclosures in 0.01 seconds.
2021-11-11 12:03:50,945 - INFO    - terrariumEngine       - TerrariumPI is up and running at address: http://0.0.0.0:8090 in 20.16 seconds.
```

So far I really like it as in future I will move from a Pi3B to Pi4 and this removes the install time.

The install can be made as simple as copying this `docker-compose.yaml` and then running `docker-compose up -d` which pulls the image, runs the container and gets you up and running in around 5 minutes (depending on internet speed)
```yaml
version: "3.3"
services:
  terrariumpi:
    image: theyosh/terrariumpi:4.0.0
    volumes:
      - /terrariumpi.db:/TerrariumPI/terrariumpi.db
      - /terrariumpi.db-shm:/TerrariumPI/terrariumpi.db-shm
      - /terrariumpi.db-wal:/TerrariumPI/terrariumpi.db-wal
    network_mode: host
    restart: always
    privileged: true
```
It should also help alot when testing and performing upgrades between new versions I think.

side note: I seen a couple of issues around bullseye, the good thing about docker is it should prevent those in future (not that they come up often).

**Comment by theyosh** [comment]
And thanks for starting this... Now I hope the docker image will work for others well. Will make a new release somewhere next week

**Comment by theyosh** [comment]
I managed to reduce the docker image below 400MB :) https://hub.docker.com/r/theyosh/terrariumpi/tags

**Comment by alec-pinson** [comment]
Nice this is really good! I will switch to this image 😊

**Comment by theyosh** [comment]
Hi, I have changed the Docker build so that it can use pre-compiled python libraries from piwheels. And this will speedup the built so fast that it now only takes 10 minutes to build :) :) Also the size has reduced a lot to 273MB compressed. A reduction of more then 100MB.

But, are you able to test this for me? It is on the branch svelte. https://github.com/theyosh/TerrariumPI/tree/svelte and https://hub.docker.com/layers/theyosh/terrariumpi/svelte/images/sha256-1c3091753c0fafcaf643e9c3756e29f7498f44c34f7be7cb853a24db37ffb235?context=explore

For me, it works. I can run it, and as far I can test, it still all works. So if you are also able to test this, then I think the rewrite is correct. And we have a fast building image and reduced the image size a lot.

**Comment by alec-pinson** [comment]
> Hi, I have changed the Docker build so that it can use pre-compiled python libraries from piwheels. And this will speedup the built so fast that it now only takes 10 minutes to build :) :) Also the size has reduced a lot to 273MB compressed. A reduction of more then 100MB.
> 
> But, are you able to test this for me? It is on the branch svelte. https://github.com/theyosh/TerrariumPI/tree/svelte and https://hub.docker.com/layers/theyosh/terrariumpi/svelte/images/sha256-1c3091753c0fafcaf643e9c3756e29f7498f44c34f7be7cb853a24db37ffb235?context=explore
> 
> For me, it works. I can run it, and as far I can test, it still all works. So if you are also able to test this, then I think the rewrite is correct. And we have a fast building image and reduced the image size a lot.

I'll test it when I get home if I remember 👍

**Comment by alec-pinson** [comment]
I get stuck in a boot loop.... 
```
pi@terrarium-pi:~ $ docker logs -f pi_terrariumpi_1
Some settings have been updated that require reboot, your Raspberry Pi will reboot in 60 seconds...
```
My `/boot/config.txt` seems to change to all on one line which causes these bits of code to break:
https://github.com/theyosh/TerrariumPI/blob/svelte/run.sh#L29

I rolled back to `4.3.0` which I'm currently running and it is ok. I can't debug fully at the moment but maybe you know why it is being changed to 1 line anyway?

**Comment by theyosh** [comment]
Hmm, that does not look right. That line has not changed for many versions. So I guess it is something else. I update the run.sh with some more output to see what it changes.

Could you upload your current /boot/config.txt file so I can see what you currently have. And spot a difference which is not expected.

I just tested with the clean legacy OS and that seems to install and start. So for me, the docker installer is working.

```
docker compose logs -f
tp4-terrariumpi-1  | Enabled I2C in boot config
tp4-terrariumpi-1  | Enable I2C modules
tp4-terrariumpi-1  | Enabled 1 Wire in boot config
tp4-terrariumpi-1  | Enabled Camera in boot config (1)
tp4-terrariumpi-1  | Enabled Camera in boot config (2)
tp4-terrariumpi-1  | Enabled Serial in boot config
tp4-terrariumpi-1  | Enabled CO2 sensors in boot config (2)
tp4-terrariumpi-1  | Some settings have been updated that require reboot, your Raspberry Pi will reboot in 60 seconds...
tp4-terrariumpi-1  | 2022-10-31 21:31:38,823 - INFO    - terrariumEngine       - Starting TerrariumPI 4.5.0 ...
tp4-terrariumpi-1  | 2022-10-31 21:31:38,981 - INFO    - terrariumEngine       - Loaded 29 settings in 0.16 seconds.
tp4-terrariumpi-1  | 2022-10-31 21:43:34,679 - INFO    - terrariumEngine       - Loading existing sensors from database.
tp4-terrariumpi-1  | 2022-10-31 21:43:34,686 - INFO    - terrariumEngine       - Scanning for new sensors ...
tp4-terrariumpi-1  | 2022-10-31 21:43:42,483 - INFO    - terrariumEngine       - Added new new sensor miflora temperature named 'MiFlora bluetooth sensor measuring temperature' at address '80:ea:ca:88:d4:d4' to database with value 22.90C in 0.31 seconds.
tp4-terrariumpi-1  | 2022-10-31 21:43:42,491 - INFO    - terrariumEngine       - Added new new sensor miflora light named 'MiFlora bluetooth sensor measuring light' at address '80:ea:ca:88:d4:d4' to database with value 3368.00lux in 0.00 seconds.
tp4-terrariumpi-1  | 2022-10-31 21:43:42,496 - INFO    - terrariumEngine       - Added new new sensor miflora moisture named 'MiFlora bluetooth sensor measuring moisture' at address '80:ea:ca:88:d4:d4' to database with value 45.00% in 0.00 seconds.
tp4-terrariumpi-1  | 2022-10-31 21:43:42,500 - INFO    - terrariumEngine       - Added new new sensor miflora fertility named 'MiFlora bluetooth sensor measuring fertility' at address '80:ea:ca:88:d4:d4' to database with value 223.00µS/cm in 0.00 seconds.
tp4-terrariumpi-1  | 2022-10-31 21:43:44,818 - INFO    - terrariumEngine       - Added new new sensor miflora temperature named 'MiFlora bluetooth sensor measuring temperature' at address 'c4:7c:8d:67:11:40' to database with value 20.70C in 0.40 seconds.
tp4-terrariumpi-1  | 2022-10-31 21:43:44,830 - INFO    - terrariumEngine       - Added new new sensor miflora light named 'MiFlora bluetooth sensor measuring light' at address 'c4:7c:8d:67:11:40' to database with value 90.00lux in 0.01 seconds.
tp4-terrariumpi-1  | 2022-10-31 21:43:44,840 - INFO    - terrariumEngine       - Added new new sensor miflora moisture named 'MiFlora bluetooth sensor measuring moisture' at address 'c4:7c:8d:67:11:40' to database with value 59.00% in 0.01 seconds.
tp4-terrariumpi-1  | 2022-10-31 21:43:44,848 - INFO    - terrariumEngine       - Added new new sensor miflora fertility named 'MiFlora bluetooth sensor measuring fertility' at address 'c4:7c:8d:67:11:40' to database with value 1380.00µS/cm in 0.01 seconds.
tp4-terrariumpi-1  | 2022-10-31 21:43:46,951 - INFO    - terrariumEngine       - Added new new sensor miflora temperature named 'MiFlora bluetooth sensor measuring temperature' at address 'c4:7c:8d:66:e3:52' to database with value 22.20C in 0.34 seconds.
tp4-terrariumpi-1  | 2022-10-31 21:43:46,959 - INFO    - terrariumEngine       - Added new new sensor miflora light named 'MiFlora bluetooth sensor measuring light' at address 'c4:7c:8d:66:e3:52' to database with value 1714.00lux in 0.00 seconds.
tp4-terrariumpi-1  | 2022-10-31 21:43:46,964 - INFO    - terrariumEngine       - Added new new sensor miflora moisture named 'MiFlora bluetooth sensor measuring moisture' at address 'c4:7c:8d:66:e3:52' to database with value 36.00% in 0.00 seconds.
tp4-terrariumpi-1  | 2022-10-31 21:43:46,969 - INFO    - terrariumEngine       - Added new new sensor miflora fertility named 'MiFlora bluetooth sensor measuring fertility' at address 'c4:7c:8d:66:e3:52' to database with value 287.00µS/cm in 0.00 seconds.
tp4-terrariumpi-1  | 2022-10-31 21:43:50,018 - INFO    - terrariumEngine       - Loaded 12 sensors in 15.34 seconds.
tp4-terrariumpi-1  | 2022-10-31 21:43:50,019 - INFO    - terrariumEngine       - Loading existing relays from database.
tp4-terrariumpi-1  | 2022-10-31 21:43:50,040 - INFO    - terrariumEngine       - Scanning for new relays ...
tp4-terrariumpi-1  | 2022-10-31 21:43:52,045 - INFO    - terrariumEngine       - Added new relay eg-pm-usb relay named 'Energenie USB device nr: 1(01:ff:ff:ff:ff), Socket: 1' at address '1,01:ff:ff:ff:ff' to database with current value 0.00.
tp4-terrariumpi-1  | 2022-10-31 21:43:52,167 - INFO    - terrariumEngine       - Added new relay eg-pm-usb relay named 'Energenie USB device nr: 1(01:ff:ff:ff:ff), Socket: 2' at address '2,01:ff:ff:ff:ff' to database with current value 0.00.
tp4-terrariumpi-1  | 2022-10-31 21:43:52,280 - INFO    - terrariumEngine       - Added new relay eg-pm-usb relay named 'Energenie USB device nr: 1(01:ff:ff:ff:ff), Socket: 3' at address '3,01:ff:ff:ff:ff' to database with current value 100.00.
tp4-terrariumpi-1  | 2022-10-31 21:43:52,388 - INFO    - terrariumEngine       - Added new relay eg-pm-usb relay named 'Energenie USB device nr: 1(01:ff:ff:ff:ff), Socket: 4' at address '4,01:ff:ff:ff:ff' to database with current value 0.00.
tp4-terrariumpi-1  | 2022-10-31 21:43:52,778 - INFO    - terrariumEngine       - Added new relay ftdi relay named 'FTDI devices device nr: 1(A702JH8H) socket: 1' at address '1,A702JH8H' to database with current value 0.00.
tp4-terrariumpi-1  | 2022-10-31 21:43:53,005 - INFO    - terrariumEngine       - Added new relay ftdi relay named 'FTDI devices device nr: 1(A702JH8H) socket: 2' at address '2,A702JH8H' to database with current value 0.00.
tp4-terrariumpi-1  | 2022-10-31 21:43:53,204 - INFO    - terrariumEngine       - Added new relay ftdi relay named 'FTDI devices device nr: 1(A702JH8H) socket: 3' at address '3,A702JH8H' to database with current value 0.00.
tp4-terrariumpi-1  | 2022-10-31 21:43:53,402 - INFO    - terrariumEngine       - Added new relay ftdi relay named 'FTDI devices device nr: 1(A702JH8H) socket: 4' at address '4,A702JH8H' to database with current value 0.00.
tp4-terrariumpi-1  | 2022-10-31 21:44:04,638 - INFO    - terrariumEngine       - Added new relay wemo relay named 'WEMO Smart plug wemotest device ip: 192.168.5.61(6038E0E8E5A0)' at address '192.168.5.61' to database with current value 0.00.
tp4-terrariumpi-1  | 2022-10-31 21:44:04,638 - INFO    - terrariumEngine       - Loaded 9 relays in 14.62 seconds.
tp4-terrariumpi-1  | 2022-10-31 21:44:04,639 - INFO    - terrariumEngine       - Loading existing buttons from database.
tp4-terrariumpi-1  | 2022-10-31 21:44:04,647 - INFO    - terrariumEngine       - Loaded 0 buttons in 0.01 seconds.
tp4-terrariumpi-1  | 2022-10-31 21:44:04,648 - INFO    - terrariumEngine       - Loading existing webcams from database.
tp4-terrariumpi-1  | 2022-10-31 21:44:04,654 - INFO    - terrariumEngine       - Loaded 0 webcams in 0.01 seconds.
tp4-terrariumpi-1  | 2022-10-31 21:44:04,655 - INFO    - terrariumEngine       - Loading existing enclosures from database.
tp4-terrariumpi-1  | 2022-10-31 21:44:04,660 - INFO    - terrariumEngine       - Loaded 0 enclosures in 0.00 seconds.
tp4-terrariumpi-1  | 2022-10-31 21:44:04,853 - INFO    - terrariumEngine       - TerrariumPI is up and running at address: http://0.0.0.0:8090 in 747.26 seconds.
```

**Comment by alec-pinson** [comment]
From having a quick look I think it's an issue with the sed commands for some reason they convert my boot config to all on a single line

I think options are
1. fix the sed command
2. update the greps to look for both ^startOfLine and ' spaceBeforeWord'

I will try have a proper look when I get some time though and push a fix if I can.

I think it maybe started after 4.3.0 but haven't narrowed down the version. I'm running bullseye btw I think

**Comment by alec-pinson** [comment]
The extra output though is definitely really useful, I was copying commands manually to check which might cause the issue

**Comment by theyosh** [comment]
If you do want to do some tests, could you use the `svelte` branch? That would be the next version, and has the 10 min docker build.

**Comment by alec-pinson** [comment]
> 

Will do

**Comment by theyosh** [comment]
Yeah, I have the single line bug also. That is on Bullseye. Buster (legacy) does not have this issue.... strange...

**Comment by theyosh** [comment]
It looks that 
```
tp4-terrariumpi-1  | Enabled Bullseye legacy Camera mode in boot config (1)
tp4-terrariumpi-1  | Enabled Bullseye legacy Camera mode in boot config (3)
``
is causing it....

**Comment by theyosh** [comment]
Fixed!! The latest svelte image is now at least starting and working in the basics.

**Comment by theyosh** [comment]
But this image is broken with OpenCV. That was the big gamble in this image. For the Buster OS it works... for Bullseye it does not.

**Comment by theyosh** [comment]
So make sure you can go back and have some backups

**Comment by theyosh** [comment]
Ok, final update. It seems that fow Bullseye you have to leave out the following 1 mount in the docker-compose.yml file:

```yml
- /opt/vc:/opt/vc
```

But again, I do not know if the camera will work then. But the image will start and the /boot/config.txt is still ok.

**Comment by alec-pinson** [comment]
Doesn't look to be fixed... although it doesn't mess up my `/boot/config.txt` anymore

```bash
pi@terrarium-pi:~ $ docker ps
CONTAINER ID   IMAGE                        COMMAND                  CREATED         STATUS                          PORTS     NAMES
9f9715083f11   theyosh/terrariumpi:svelte   "/bin/bash /Terrariu…"   4 minutes ago   Restarting (100) 1 second ago             pi_terrariumpi_1

pi@terrarium-pi:~ $ docker logs -f pi_terrariumpi_1
Enabled Bullseye legacy Camera mode in boot config (3)
Enabled Serial in boot config
Some settings have been updated that require reboot, please reboot your Raspberry Pi now.
Enabled Bullseye legacy Camera mode in boot config (3)
Some settings have been updated that require reboot, please reboot your Raspberry Pi now.
Enabled Bullseye legacy Camera mode in boot config (3)
Some settings have been updated that require reboot, please reboot your Raspberry Pi now.
Enabled Bullseye legacy Camera mode in boot config (3)

pi@terrarium-pi:~ $ cat /boot/config.txt
dtparam=i2c_arm=on
dtoverlay=w1-gpio
gpu_mem=128
start_x=1
enable_uart=1
```

**Comment by theyosh** [comment]
Ah, you have stripped down that file. I was looking for a [pi4] section. So the latest `svelte` version should take that in account and just skip that change. So if you have time to test one time more, that would be very great.

**Comment by alec-pinson** [comment]
Tested and it's working now! :)
