### ISSUE TITLE
[BUG]: No Startup after Upgrade 

### ISSUE THREAD

**Issue by Konrad84** [theyosh/TerrariumPI#922]
Hi Yosh,

thank you for your developement !

I got a problem. I tried to upgrade my TerrariumPI during the Upgrade Process there was some red signs about missing files or something. After Update and reboot i can´t start Terrarium PI. I can get into the Folder but no reaction if i try sudo service terrariumPI start oder sudo ./ run.sh etc. .

Have you an idea what i can do?

**Comment by theyosh** [comment]
the ./runs.sh should not be run. Not sure what it will do on a Pi, but that is for Docker.

But you should be able to rerun the installer.

So what happens when you just run `./install.sh` again?

And than run it in debug mode: https://theyosh.github.io/TerrariumPI/faq/how-to-debug-terrariumpi/

And did you made a backup of your database? https://theyosh.github.io/TerrariumPI/faq/which-files-to-backup/ So you could reinstall the software at all.

**Comment by Konrad84** [comment]
ok that worked now i get this during debug

pi@raspberrypi:~/TerrariumPI $ source venv/bin/activate
(venv) pi@raspberrypi:~/TerrariumPI $ python terrariumPI.py
2024-06-06 22:05:11,746 - INFO    - terrariumEngine       - Starting up Terrariu                                                                                                                                                             mPI 4.9.0 on a Raspberry Pi 3 Model B Rev 1.2 ...
2024-06-06 22:05:11,788 - INFO    - terrariumEngine       - Loaded 32 settings i                                                                                                                                                             n 0.04 seconds.
2024-06-06 22:05:12,852 - INFO    - OpenWeatherMap        - Using Openweathermap                                                                                                                                                              Free API
2024-06-06 22:05:12,855 - INFO    - terrariumWeather      - Loaded weather data                                                                                                                                                              from source https://api.openweathermap.org/data/2.5/weather?q=Erding,DE&appid=de                                                                                                                                                             7a1fbd5f74afc83284ce53b8c9b504 in 1.02 seconds
/home/pi/TerrariumPI/terrariumNotification.py:2742: PTBUserWarning: If 'per_mess                                                                                                                                                             age=False', 'CallbackQueryHandler' will not be tracked for every message. Read t                                                                                                                                                             his FAQ entry to learn more about the per_* settings: https://github.com/python-                                                                                                                                                             telegram-bot/python-telegram-bot/wiki/Frequently-Asked-Questions#what-do-the-per                                                                                                                                                             _-settings-in-conversationhandler-do.
  ConversationHandler(
/home/pi/TerrariumPI/terrariumNotification.py:2749: PTBUserWarning: If 'per_mess                                                                                                                                                             age=False', 'CallbackQueryHandler' will not be tracked for every message. Read t                                                                                                                                                             his FAQ entry to learn more about the per_* settings: https://github.com/python-                                                                                                                                                             telegram-bot/python-telegram-bot/wiki/Frequently-Asked-Questions#what-do-the-per                                                                                                                                                             _-settings-in-conversationhandler-do.
  ConversationHandler(
^CTraceback (most recent call last):
  File "/home/pi/TerrariumPI/terrariumPI.py", line 27, in <module>
    terrariumEngine = terrariumEngine(__version__)
  File "/home/pi/TerrariumPI/terrariumEngine.py", line 135, in __init__
    self.calendar = terrariumCalendar()
  File "/home/pi/TerrariumPI/terrariumCalendar.py", line 34, in __init__
    for event in self.get_events(
  File "/home/pi/TerrariumPI/terrariumCalendar.py", line 75, in get_events
    for event_data in events(string_content=self.__ical.to_ical(), start=start, end=end):
  File "/home/pi/TerrariumPI/venv/lib/python3.9/site-packages/icalevents/icalevents.py", line 57, in events
    found_events += parse_events(
  File "/home/pi/TerrariumPI/venv/lib/python3.9/site-packages/icalevents/icalparser.py", line 391, in parse_events
    if not event.recurrence_id and (event.uid, event.start) in [
  File "/home/pi/TerrariumPI/venv/lib/python3.9/site-packages/icalevents/icalparser.py", line 392, in <listcomp>
    (f.uid, f.recurrence_id) for f in found
KeyboardInterrupt
2024-06-06 22:07:08,116 - WARNING - terrariumNotification - Error connecting to Telegram. Just retry once more: Timed out
2024-06-06 22:07:08,126 - ERROR   - terrariumNotification - Error connecting to Telegram: Unknown error in HTTP implementation: RuntimeError('cannot schedule new futures after interpreter shutdown')
^CKeyboardInterrupt
2024-06-06T20:08:00Z
Exception ignored in: <module 'threading' from '/usr/lib/python3.9/threading.py'>
Traceback (most recent call last):
  File "/home/pi/TerrariumPI/venv/lib/python3.9/site-packages/gevent/monkey.py", line 868, in _shutdown
    orig_shutdown()
  File "/usr/lib/python3.9/threading.py", line 1428, in _shutdown
    lock.acquire()
  File "/home/pi/TerrariumPI/venv/lib/python3.9/site-packages/gevent/thread.py", line 112, in acquire
    acquired = BoundedSemaphore.acquire(self, blocking, timeout)
  File "src/gevent/_semaphore.py", line 184, in gevent._gevent_c_semaphore.Semaphore.acquire
  File "src/gevent/_semaphore.py", line 253, in gevent._gevent_c_semaphore.Semaphore.acquire
  File "src/gevent/_abstract_linkable.py", line 521, in gevent._gevent_c_abstract_linkable.AbstractLinkable._wait
  File "src/gevent/_abstract_linkable.py", line 487, in gevent._gevent_c_abstract_linkable.AbstractLinkable._wait_core
  File "src/gevent/_abstract_linkable.py", line 490, in gevent._gevent_c_abstract_linkable.AbstractLinkable._wait_core
  File "src/gevent/_abstract_linkable.py", line 442, in gevent._gevent_c_abstract_linkable.AbstractLinkable._AbstractLinkable__wait_to_be_notified
  File "src/gevent/_abstract_linkable.py", line 451, in gevent._gevent_c_abstract_linkable.AbstractLinkable._switch_to_hub
  File "src/gevent/_greenlet_primitives.py", line 61, in gevent._gevent_c_greenlet_primitives.SwitchOutGreenletWithLoop.switch
  File "src/gevent/_greenlet_primitives.py", line 65, in gevent._gevent_c_greenlet_primitives.SwitchOutGreenletWithLoop.switch
  File "src/gevent/_gevent_c_greenlet_primitives.pxd", line 35, in gevent._gevent_c_greenlet_primitives._greenlet_switch
KeyboardInterrupt:

**Comment by theyosh** [comment]
You stopped to early.. There was no error with telegram... just a message. Please keep it running until it says it is started and webgui available

**Comment by Konrad84** [comment]
oh ok sorry i ll try again

**Comment by Konrad84** [comment]
ok i waited about 30 min. and it stops at this point

pi@raspberrypi:~ $ cd TerrariumPI
pi@raspberrypi:~/TerrariumPI $ source venv/bin/activate
(venv) pi@raspberrypi:~/TerrariumPI $ python terrariumPI.py
2024-06-06 22:40:12,957 - INFO    - terrariumEngine       - Starting up Terrariu                                                                                                                                                             mPI 4.9.0 on a Raspberry Pi 3 Model B Rev 1.2 ...
2024-06-06 22:40:12,999 - INFO    - terrariumEngine       - Loaded 32 settings i                                                                                                                                                             n 0.04 seconds.
2024-06-06 22:40:13,923 - INFO    - OpenWeatherMap        - Using Openweathermap                                                                                                                                                              Free API
2024-06-06 22:40:13,926 - INFO    - terrariumWeather      - Loaded weather data                                                                                                                                                              from source https://api.openweathermap.org/data/2.5/weather?q=Erding,DE&appid=de                                                                                                                                                             7a1fbd5f74afc83284ce53b8c9b504 in 0.88 seconds
/home/pi/TerrariumPI/terrariumNotification.py:2742: PTBUserWarning: If 'per_mess                                                                                                                                                             age=False', 'CallbackQueryHandler' will not be tracked for every message. Read t                                                                                                                                                             his FAQ entry to learn more about the per_* settings: https://github.com/python-                                                                                                                                                             telegram-bot/python-telegram-bot/wiki/Frequently-Asked-Questions#what-do-the-per                                                                                                                                                             _-settings-in-conversationhandler-do.
  ConversationHandler(
/home/pi/TerrariumPI/terrariumNotification.py:2749: PTBUserWarning: If 'per_mess                                                                                                                                                             age=False', 'CallbackQueryHandler' will not be tracked for every message. Read t                                                                                                                                                             his FAQ entry to learn more about the per_* settings: https://github.com/python-                                                                                                                                                             telegram-bot/python-telegram-bot/wiki/Frequently-Asked-Questions#what-do-the-per                                                                                                                                                             _-settings-in-conversationhandler-do.
  ConversationHandler(

**Comment by theyosh** [comment]
Hmm, looks like Telegram is causing this... That is not handy, as I cannot test it....

So we can disable Telegram for now with the following commands. Go to the database folder located in the `data` folder: `/home/pi/TerrariumPI/data`

1. `sqlite3 terrariumpi.db`
2. `update NotificationService set enabled = 0 where type = 'telegram';`
3. Press Ctrl+D

And now start in debug mode again. Make sure you change to the correct folder again.

**Comment by theyosh** [comment]
Did the above help? Was you able to disable telegram and start up TerrariumPI?

**Comment by Konrad84** [comment]
Ok now i get this 


pi@raspberrypi:~/TerrariumPI/data $ ls
calendar.ics  terrariumpi.db      terrariumpi.db-wal
terrarium.db  terrariumpi.db-shm
pi@raspberrypi:~/TerrariumPI/data $ sqlite3 terrariumpi.db
SQLite version 3.34.1 2021-01-20 14:10:07
Enter ".help" for usage hints.
sqlite> update NotificationService set enabled = 0 where type = 'telegram';                                          sqlite>

pi@raspberrypi:~/TerrariumPI/data $ cd..
-bash: cd..: Kommando nicht gefunden.
pi@raspberrypi:~/TerrariumPI/data $ cd
pi@raspberrypi:~ $ TerrariumPI
-bash: TerrariumPI: Kommando nicht gefunden.
pi@raspberrypi:~ $ cd TerrariumPI
pi@raspberrypi:~/TerrariumPI $ sudo service terrariumpi stop

cd
top
^C
pi@raspberrypi:~/TerrariumPI $ cd
pi@raspberrypi:~ $ sudo service terrariumpi stop


cd

^C
pi@raspberrypi:~ $ cd TerrariumPI
pi@raspberrypi:~/TerrariumPI $ source venv/bin/activate
(venv) pi@raspberrypi:~/TerrariumPI $ python terrariumPI.py
2024-06-08 12:01:58,671 - INFO    - terrariumEngine       - Starting up Terrariu                                     mPI 4.9.0 on a Raspberry Pi 3 Model B Rev 1.2 ...
2024-06-08 12:01:58,706 - INFO    - terrariumEngine       - Loaded 32 settings i                                     n 0.03 seconds.
2024-06-08 12:01:59,691 - INFO    - OpenWeatherMap        - Using Openweathermap                                      Free API
2024-06-08 12:01:59,694 - INFO    - terrariumWeather      - Loaded weather data                                      from source https://api.openweathermap.org/data/2.5/weather?q=Erding,DE&appid=de                                     7a1fbd5f74afc83284ce53b8c9b504 in 0.94 seconds
^CTraceback (most recent call last):
  File "/home/pi/TerrariumPI/terrariumPI.py", line 27, in <module>
    terrariumEngine = terrariumEngine(__version__)
  File "/home/pi/TerrariumPI/terrariumEngine.py", line 135, in __init__
    self.calendar = terrariumCalendar()
  File "/home/pi/TerrariumPI/terrariumCalendar.py", line 34, in __init__
    for event in self.get_events(
  File "/home/pi/TerrariumPI/terrariumCalendar.py", line 75, in get_events
    for event_data in events(string_content=self.__ical.to_ical(), start=start, end=end):
  File "/home/pi/TerrariumPI/venv/lib/python3.9/site-packages/icalevents/icalevents.py", line 57, in events
    found_events += parse_events(
  File "/home/pi/TerrariumPI/venv/lib/python3.9/site-packages/icalevents/icalparser.py", line 391, in parse_events
    if not event.recurrence_id and (event.uid, event.start) in [
  File "/home/pi/TerrariumPI/venv/lib/python3.9/site-packages/icalevents/icalparser.py", line 392, in <listcomp>
    (f.uid, f.recurrence_id) for f in found
KeyboardInterrupt

**Comment by theyosh** [comment]
Hmm, this is strange... I get the feeling a broken SD card??

But first we can try the following. Rename the calender file so it will create a new one.

`mv /home/pi/TerrariumPI/data/calander.ics /home/pi/TerrariumPI/data/calander.ics.backup`

and restart in debug mode once again. Lets see what that does.

**Comment by Konrad84** [comment]
Oh now it keeps running but with failure messages and error of the raspicam (but function was good before.. hmm

pi@raspberrypi:~ $ sudo service TerrariumPI stop
Failed to stop TerrariumPI.service: Unit TerrariumPI.service not loaded.
pi@raspberrypi:~ $ cd TerrariumPI
pi@raspberrypi:~/TerrariumPI $ source venv/bin/activate
(venv) pi@raspberrypi:~/TerrariumPI $ python terrariumPI.py
2024-06-08 20:32:49,793 - INFO    - terrariumEngine       - Starting up Terrariu                                     mPI 4.9.0 on a Raspberry Pi 3 Model B Rev 1.2 ...
2024-06-08 20:32:49,829 - INFO    - terrariumEngine       - Loaded 32 settings i                                     n 0.03 seconds.
2024-06-08 20:32:51,234 - INFO    - OpenWeatherMap        - Using Openweathermap                                      Free API
2024-06-08 20:32:51,238 - INFO    - terrariumWeather      - Loaded weather data                                      from source https://api.openweathermap.org/data/2.5/weather?q=Erding,DE&appid=de                                     7a1fbd5f74afc83284ce53b8c9b504 in 1.37 seconds
2024-06-08 20:32:52,341 - INFO    - terrariumEngine       - Start loading total                                      power and water usage
2024-06-08 20:32:54,529 - INFO    - terrariumEngine       - Loaded total power a                                     nd water usage in 2.19 seconds.
2024-06-08 20:32:54,531 - INFO    - terrariumEngine       - Loading existing sen                                     sors from database.
2024-06-08 20:32:55,558 - INFO    - terrariumSensor       - Loaded sensor 1-Wire                                      sensor temperature named 'Schildkrötenhaus' at address '28-3c01f09637c2' with v                                     alue 22.19C in 1.00 seconds.
2024-06-08 20:32:56,483 - INFO    - terrariumSensor       - Loaded sensor 1-Wire                                      sensor temperature named 'Außentemperatur' at address '28-3c01f096b371' with va                                     lue 18.31C in 0.92 seconds.
2024-06-08 20:32:57,436 - INFO    - terrariumSensor       - Loaded sensor 1-Wire                                      sensor temperature named 'Gewächshaus' at address '28-3c01f096fb7e' with value                                      20.81C in 0.95 seconds.
2024-06-08 20:32:58,397 - INFO    - terrariumSensor       - Loaded sensor 1-Wire                                      sensor temperature named 'Schildkröten Babys' at address '28-3de104572f5c' with                                      value 21.44C in 0.96 seconds.
2024-06-08 20:32:59,356 - INFO    - terrariumSensor       - Loaded sensor 1-Wire                                      sensor temperature named 'Schaltkasten (Reserve2)' at address '28-3de10457f6b5'                                      with value 20.06C in 0.96 seconds.
2024-06-08 20:32:59,364 - INFO    - terrariumEngine       - Scanning for new sen                                     sors ...
2024-06-08 20:33:13,413 - INFO    - terrariumEngine       - Loaded 5 sensors in                                      18.88 seconds.
2024-06-08 20:33:13,415 - INFO    - terrariumEngine       - Loading existing rel                                     ays from database.
2024-06-08 20:33:15,398 - INFO    - terrariumRelay        - Loaded relay gpio re                                     lay named 'DACH' at address '32' value 0.00 in 1.93 seconds.
2024-06-08 20:33:15,419 - INFO    - terrariumRelay        - Loaded relay gpio re                                     lay named 'TÜRE' at address '36' value 0.00 in 0.02 seconds.
2024-06-08 20:33:15,437 - INFO    - terrariumRelay        - Loaded relay gpio re                                     lay named 'HEIZEN' at address '38' value 0.00 in 0.02 seconds.
2024-06-08 20:33:15,455 - INFO    - terrariumRelay        - Loaded relay gpio re                                     lay named 'LICHT' at address '40' value 0.00 in 0.02 seconds.
2024-06-08 20:33:15,459 - INFO    - terrariumEngine       - Scanning for new rel                                     ays ...
No GEMBIRD SiS-PM found. Check USB connections, please!
2024-06-08 20:33:31,317 - INFO    - terrariumEngine       - Loaded 4 relays in 17.90 seconds.
2024-06-08 20:33:31,319 - INFO    - terrariumEngine       - Loading existing buttons from database.
2024-06-08 20:33:31,342 - INFO    - terrariumEngine       - Loaded 0 buttons in 0.02 seconds.
2024-06-08 20:33:31,344 - INFO    - terrariumEngine       - Loading existing webcams from database.
2024-06-08 20:33:36,471 - WARNING - hardware.webcam       - Webcam Live Raspberry PI camera named 'Haus innen' at address 'rpicam_live' is crashed. Restarting the webcam.
2024-06-08 20:33:42,051 - WARNING - hardware.webcam       - Webcam Live Raspberry PI camera named 'Haus innen' at address 'rpicam_live' is crashed. Restarting the webcam.
2024-06-08 20:33:47,620 - WARNING - hardware.webcam       - Webcam Live Raspberry PI camera named 'Haus innen' at address 'rpicam_live' is crashed. Restarting the webcam.
2024-06-08 20:33:53,194 - ERROR   - hardware.webcam       - Webcam Live Raspberry PI camera named 'Haus innen' at address 'rpicam_live' has gone offline! Please check your webcam connections.
2024-06-08 20:33:53,908 - INFO    - terrariumWebcam       - Loaded rpicam-live webcam 'Haus innen' at address 'rpicam_live' in 22.54 seconds.
[ERROR:0@67.839] global /tmp/pip-wheel-nz49_ez6/opencv-python-headless_488dea44cb7d406baf80df0bfc388ff9/opencv/modules/videoio/src/cap.cpp (164) open VIDEOIO(CV_IMAGES): raised OpenCV exception:

OpenCV(4.6.0) /tmp/pip-wheel-nz49_ez6/opencv-python-headless_488dea44cb7d406baf80df0bfc388ff9/opencv/modules/videoio/src/cap_images.cpp:293: error: (-215:Assertion failed) !_filename.empty() in function 'open'


2024-06-08 20:34:01,935 - INFO    - terrariumWebcam       - Loaded rtsp webcam 'Außengehege' at address 'rtsp://admin:admin@192.168.178.91:8554/Streaming/Channels/101' in 8.03 seconds.
2024-06-08 20:34:01,936 - INFO    - terrariumEngine       - Loaded 2 webcams in 30.59 seconds.
2024-06-08 20:34:01,937 - INFO    - terrariumEngine       - Loading existing enclosures from database.
2024-06-08 20:34:01,945 - INFO    - terrariumEngine       - Loaded 0 enclosures in 0.01 seconds.
2024-06-08 20:34:02,173 - INFO    - terrariumEngine       - Message of the Day generated in 0.23 seconds
2024-06-08 20:34:02,175 - INFO    - terrariumEngine       - TerrariumPI 4.9.0 is up and running at address: http://0.0.0.0:8090 in 73.95 seconds.
2024-06-08 20:34:02,000 - INFO    - terrariumWebserver    - Running webserver at 0.0.0.0:8090
2024-06-08 20:34:03,476 - WARNING - hardware.webcam       - Webcam Live Raspberry PI camera named 'Haus innen' at address 'rpicam_live' is crashed. Restarting the webcam.
[h264 @ 0x18677f0] error while decoding MB 106 67, bytestream -11
2024-06-08 20:34:09,226 - WARNING - hardware.sensor       - Error getting new data from sensor 1-Wire sensor temperature named 'Außentemperatur' at address '28-3c01f096b371': no data, retrying in 0.5 seconds...
[h264 @ 0x18b50f0] error while decoding MB 106 67, bytestream -11
2024-06-08 20:34:16,658 - WARNING - hardware.webcam       - Webcam Live Raspberry PI camera named 'Haus innen' at address 'rpicam_live' is crashed. Restarting the webcam.
2024-06-08 20:34:22,216 - WARNING - hardware.webcam       - Webcam Live Raspberry PI camera named 'Haus innen' at address 'rpicam_live' is crashed. Restarting the webcam.
2024-06-08 20:34:32,562 - WARNING - hardware.webcam       - Webcam Live Raspberry PI camera named 'Haus innen' at address 'rpicam_live' is crashed. Restarting the webcam.
2024-06-08 20:34:42,492 - WARNING - hardware.webcam       - Webcam Live Raspberry PI camera named 'Haus innen' at address 'rpicam_live' is crashed. Restarting the webcam.
2024-06-08 20:34:48,047 - WARNING - hardware.webcam       - Webcam Live Raspberry PI camera named 'Haus innen' at address 'rpicam_live' is crashed. Restarting the webcam.
2024-06-08 20:35:03,425 - WARNING - hardware.webcam       - Webcam Live Raspberry PI camera named 'Haus innen' at address 'rpicam_live' is crashed. Restarting the webcam.
2024-06-08 20:35:15,597 - WARNING - hardware.webcam       - Webcam Live Raspberry PI camera named 'Haus innen' at address 'rpicam_live' is crashed. Restarting the webcam.
2024-06-08 20:35:21,213 - WARNING - hardware.webcam       - Webcam Live Raspberry PI camera named 'Haus innen' at address 'rpicam_live' is crashed. Restarting the webcam.
2024-06-08 20:35:32,579 - WARNING - hardware.webcam       - Webcam Live Raspberry PI camera named 'Haus innen' at address 'rpicam_live' is crashed. Restarting the webcam.
2024-06-08 20:35:42,040 - WARNING - hardware.webcam       - Webcam Live Raspberry PI camera named 'Haus innen' at address 'rpicam_live' is crashed. Restarting the webcam.
2024-06-08 20:35:47,597 - WARNING - hardware.webcam       - Webcam Live Raspberry PI camera named 'Haus innen' at address 'rpicam_live' is crashed. Restarting the webcam.
2024-06-08 20:36:03,422 - WARNING - hardware.webcam       - Webcam Live Raspberry PI camera named 'Haus innen' at address 'rpicam_live' is crashed. Restarting the webcam.
2024-06-08 20:36:15,050 - WARNING - hardware.webcam       - Webcam Live Raspberry PI camera named 'Haus innen' at address 'rpicam_live' is crashed. Restarting the webcam.
2024-06-08 20:36:20,666 - WARNING - hardware.webcam       - Webcam Live Raspberry PI camera named 'Haus innen' at address 'rpicam_live' is crashed. Restarting the webcam.
2024-06-08 20:36:32,596 - WARNING - hardware.webcam       - Webcam Live Raspberry PI camera named 'Haus innen' at address 'rpicam_live' is crashed. Restarting the webcam.
2024-06-08 20:36:41,284 - WARNING - hardware.webcam       - Webcam Live Raspberry PI camera named 'Haus innen' at address 'rpicam_live' is crashed. Restarting the webcam.
/home/pi/TerrariumPI/venv/lib/python3.9/site-packages/bottle.py:3383: DeprecationWarning: Absolute template path names are deprecated.
  fname = self.search(name, self.lookup)
2024-06-08 20:36:46,870 - WARNING - hardware.webcam       - Webcam Live Raspberry PI camera named 'Haus innen' at address 'rpicam_live' is crashed. Restarting the webcam.
2024-06-08 20:37:03,515 - WARNING - hardware.webcam       - Webcam Live Raspberry PI camera named 'Haus innen' at address 'rpicam_live' is crashed. Restarting the webcam.
2024-06-08 20:37:14,087 - WARNING - hardware.webcam       - Webcam Live Raspberry PI camera named 'Haus innen' at address 'rpicam_live' is crashed. Restarting the webcam.
2024-06-08 20:37:19,708 - WARNING - hardware.webcam       - Webcam Live Raspberry PI camera named 'Haus innen' at address 'rpicam_live' is crashed. Restarting the webcam.
2024-06-08 20:37:32,601 - WARNING - hardware.webcam       - Webcam Live Raspberry PI camera named 'Haus innen' at address 'rpicam_live' is crashed. Restarting the webcam.
2024-06-08 20:37:40,645 - WARNING - hardware.webcam       - Webcam Live Raspberry PI camera named 'Haus innen' at address 'rpicam_live' is crashed. Restarting the webcam.
2024-06-08 20:37:46,225 - WARNING - hardware.webcam       - Webcam Live Raspberry PI camera named 'Haus innen' at address 'rpicam_live' is crashed. Restarting the webcam.
2024-06-08 20:38:03,513 - WARNING - hardware.webcam       - Webcam Live Raspberry PI camera named 'Haus innen' at address 'rpicam_live' is crashed. Restarting the webcam.
2024-06-08 20:38:13,450 - WARNING - hardware.webcam       - Webcam Live Raspberry PI camera named 'Haus innen' at address 'rpicam_live' is crashed. Restarting the webcam.
2024-06-08 20:38:19,196 - WARNING - hardware.webcam       - Webcam Live Raspberry PI camera named 'Haus innen' at address 'rpicam_live' is crashed. Restarting the webcam.
^CKeyboardInterrupt
2024-06-08T18:38:23Z
2024-06-08 20:38:23,256 - INFO    - terrariumEngine       - Stopping TerrariumPI 4.9.0 ...
2024-06-08 20:38:23,260 - INFO    - terrariumEngine       - Stopped log tailing.
2024-06-08 20:38:24,775 - INFO    - terrariumWebcam       - Updated webcam rpicam-live webcam 'Haus innen' at address 'rpicam_live' in 21.27 seconds.
2024-06-08 20:38:24,998 - INFO    - terrariumEngine       - Message of the Day generated in 0.21 seconds
2024-06-08 20:38:25,080 - INFO    - terrariumEngine       - Engine update done in 22.60 seconds. Waiting for 7.40 seconds for the next round.
2024-06-08 20:38:25,082 - INFO    - terrariumEngine       - Stopped main engine thread
2024-06-08 20:38:25,085 - INFO    - terrariumEngine       - Stopped 1-Wire sensor temperature named 'Schildkrötenhaus' at address '28-3c01f09637c2'
2024-06-08 20:38:25,086 - INFO    - terrariumEngine       - Stopped 1-Wire sensor temperature named 'Außentemperatur' at address '28-3c01f096b371'
2024-06-08 20:38:25,087 - INFO    - terrariumEngine       - Stopped 1-Wire sensor temperature named 'Gewächshaus' at address '28-3c01f096fb7e'
2024-06-08 20:38:25,088 - INFO    - terrariumEngine       - Stopped 1-Wire sensor temperature named 'Schildkröten Babys' at address '28-3de104572f5c'
2024-06-08 20:38:25,088 - INFO    - terrariumEngine       - Stopped 1-Wire sensor temperature named 'Schaltkasten (Reserve2)' at address '28-3de10457f6b5'
2024-06-08 20:38:25,091 - INFO    - terrariumEngine       - Stopped GPIO devices relay named 'DACH' at address '32'
2024-06-08 20:38:25,094 - INFO    - terrariumEngine       - Stopped GPIO devices relay named 'TÜRE' at address '36'
2024-06-08 20:38:25,096 - INFO    - terrariumEngine       - Stopped GPIO devices relay named 'HEIZEN' at address '38'
2024-06-08 20:38:25,098 - INFO    - terrariumEngine       - Stopped GPIO devices relay named 'LICHT' at address '40'
2024-06-08 20:38:25,100 - INFO    - terrariumEngine       - Stopped Live Raspberry PI camera named 'Haus innen' at address 'rpicam_live'
2024-06-08 20:38:25,100 - INFO    - terrariumEngine       - Stopped RTSP camera named 'Außengehege' at address 'rtsp://admin:admin@192.168.178.91:8554/Streaming/Channels/101'
2024-06-08 20:38:25,101 - INFO    - terrariumEngine       - Stopped TerrariumPI 4.9.0 after running for 0:05:36. Bye bye.

**Comment by theyosh** [comment]
Hmm, ok, strange. But for now it will start.

For the webcam we can try to trouble shoot in a different issue.

Not sure why the telegram and the calendar file was causing issues.....

**Comment by theyosh** [comment]
What you could do is a reboot of the PI. That could be the trick to start the webcam again. If that does not work for you, please open a new issue to trouble shout the webcam.

**Comment by Konrad84** [comment]
Hi yes it works now but i decided to upgrade to 4.9.1. now .. maybe there are additional issues with the installation i get several hints like this .. 

![image](https://github.com/theyosh/TerrariumPI/assets/104820070/209dff23-716f-40b8-820d-a435a6b58f91)

**Comment by Konrad84** [comment]
Maybe tr a new SD .. Hmm ..

**Comment by Konrad84** [comment]
ok upgrade worked but now all relays are gone and scan says 0 found. No Cameras. Sensors are good i think.

Have you an idea what i can do or have i get a new setup SD and maybe Raspberry?

**Comment by Konrad84** [comment]
(venv) pi@raspberrypi:~/TerrariumPI $ python terrariumPI.py
2024-06-09 12:44:01,506 - INFO    - terrariumEngine       - Starting up Terrariu                                     mPI 4.9.1 on a Raspberry Pi 3 Model B Rev 1.2 ...
2024-06-09 12:44:01,541 - INFO    - terrariumEngine       - Loaded 32 settings i                                     n 0.03 seconds.
2024-06-09 12:44:02,668 - INFO    - terrariumEngine       - Start loading total                                      power and water usage
2024-06-09 12:44:03,705 - INFO    - terrariumEngine       - Loaded total power a                                     nd water usage in 1.04 seconds.
2024-06-09 12:44:03,707 - INFO    - terrariumEngine       - Loading existing sen                                     sors from database.
2024-06-09 12:44:04,753 - INFO    - terrariumSensor       - Loaded sensor 1-Wire                                      sensor temperature named '1-Wire sensor measuring temperature' at address '28-3                                     c01f09637c2' with value 21.69C in 1.02 seconds.
2024-06-09 12:44:05,673 - INFO    - terrariumSensor       - Loaded sensor 1-Wire                                      sensor temperature named '1-Wire sensor measuring temperature' at address '28-3                                     c01f096b371' with value 21.38C in 0.92 seconds.
2024-06-09 12:44:06,631 - INFO    - terrariumSensor       - Loaded sensor 1-Wire                                      sensor temperature named '1-Wire sensor measuring temperature' at address '28-3                                     c01f096fb7e' with value 21.94C in 0.96 seconds.
2024-06-09 12:44:07,591 - INFO    - terrariumSensor       - Loaded sensor 1-Wire                                      sensor temperature named '1-Wire sensor measuring temperature' at address '28-3                                     de104572f5c' with value 30.88C in 0.96 seconds.
2024-06-09 12:44:08,551 - INFO    - terrariumSensor       - Loaded sensor 1-Wire                                      sensor temperature named '1-Wire sensor measuring temperature' at address '28-3                                     de10457f6b5' with value 27.19C in 0.96 seconds.
2024-06-09 12:44:08,556 - INFO    - terrariumEngine       - Scanning for new sen                                     sors ...
2024-06-09 12:44:22,643 - INFO    - terrariumEngine       - Loaded 5 sensors in 18.94 seconds.
2024-06-09 12:44:22,645 - INFO    - terrariumEngine       - Loading existing relays from database.
2024-06-09 12:44:22,663 - INFO    - terrariumEngine       - Scanning for new relays ...
No GEMBIRD SiS-PM found. Check USB connections, please!
2024-06-09 12:44:39,614 - INFO    - terrariumEngine       - Loaded 0 relays in 16.97 seconds.
2024-06-09 12:44:39,616 - INFO    - terrariumEngine       - Loading existing buttons from database.
2024-06-09 12:44:39,640 - INFO    - terrariumEngine       - Loaded 0 buttons in 0.02 seconds.
2024-06-09 12:44:39,642 - INFO    - terrariumEngine       - Loading existing webcams from database.
2024-06-09 12:44:39,672 - INFO    - terrariumEngine       - Loaded 0 webcams in 0.03 seconds.
2024-06-09 12:44:39,674 - INFO    - terrariumEngine       - Loading existing enclosures from database.
2024-06-09 12:44:39,687 - INFO    - terrariumEngine       - Loaded 0 enclosures in 0.01 seconds.
2024-06-09 12:44:39,849 - INFO    - terrariumEngine       - Message of the Day generated in 0.16 seconds
2024-06-09 12:44:39,857 - INFO    - terrariumEngine       - TerrariumPI 4.9.1 is up and running at address: http://0.0.0.0:8090 in 39.92 seconds.
2024-06-09 12:44:39,000 - INFO    - terrariumWebserver    - Running webserver at 0.0.0.0:8090

**Comment by theyosh** [comment]
> Hi yes it works now but i decided to upgrade to 4.9.1. now .. maybe there are additional issues with the installation i get several hints like this ..
> 
> ![image](https://private-user-images.githubusercontent.com/104820070/337964906-209dff23-716f-40b8-820d-a435a6b58f91.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc5MzE1MDUsIm5iZiI6MTcxNzkzMTIwNSwicGF0aCI6Ii8xMDQ4MjAwNzAvMzM3OTY0OTA2LTIwOWRmZjIzLTcxNmYtNDBiOC04MjBkLWE0MzVhNmI1OGY5MS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwOVQxMTA2NDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xYzZlNDVkNzgyZTRlNzk2YjRiM2M5OWU0MTQ4MWIyYTc5NDQ5ZGM2ZTBkOTY1YTg4ZTliNTlmMzIwNzkyZTA2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Mk0-pUS4eLi-FrLX7TLy_rOsEvWukMhoxfqrN_e26-A)

Hmm, you have German language and locale in use... That could explain a bit.

**Comment by Konrad84** [comment]
Hmm what do you mean about language. Should i Change Something ?

**Comment by theyosh** [comment]
> Hmm what do you mean about language. Should i Change Something ?

Nope, but in German you use a comma for decimals, and I used a dot. So than it does not work. So I made the code now language aware. And now the strange error during installation should be fixed.

So you do not have to change anything. But I did not test with a different language which uses different decimal notation.

**Comment by theyosh** [comment]
Everything is still running?

**Comment by Konrad84** [comment]
Hi Just Sensors are running camera and Relais are offline /deleted. Maybe i Just need to set things Up new.. but i think WE can Close this issue and i create a new one for the cameras If i cant fix it ;) thank you Am 12.06.2024 22:05 schrieb TheYOSH ***@***.***>:
Everything is still running?
